export const TIMEZONES = [
  // Americas
  { value: "America/New_York", label: "Eastern Time (ET)", offset: "UTC-5/-4" },
  { value: "America/Chicago", label: "Central Time (CT)", offset: "UTC-6/-5" },
  { value: "America/Denver", label: "Mountain Time (MT)", offset: "UTC-7/-6" },
  { value: "America/Los_Angeles", label: "Pacific Time (PT)", offset: "UTC-8/-7" },
  { value: "America/Anchorage", label: "Alaska Time (AKT)", offset: "UTC-9/-8" },
  { value: "Pacific/Honolulu", label: "Hawaii Time (HT)", offset: "UTC-10" },
  { value: "America/Toronto", label: "Toronto, Canada", offset: "UTC-5/-4" },
  { value: "America/Vancouver", label: "Vancouver, Canada", offset: "UTC-8/-7" },
  { value: "America/Mexico_City", label: "Mexico City, Mexico", offset: "UTC-6/-5" },
  { value: "America/Sao_Paulo", label: "São Paulo, Brazil", offset: "UTC-3/-2" },
  { value: "America/Argentina/Buenos_Aires", label: "Buenos Aires, Argentina", offset: "UTC-3" },
  { value: "America/Lima", label: "Lima, Peru", offset: "UTC-5" },
  { value: "America/Santiago", label: "Santiago, Chile", offset: "UTC-4/-3" },
  { value: "America/Bogota", label: "Bogotá, Colombia", offset: "UTC-5" },
  { value: "America/Caracas", label: "Caracas, Venezuela", offset: "UTC-4" },

  // Europe
  { value: "Europe/London", label: "London, UK", offset: "UTC+0/+1" },
  { value: "Europe/Paris", label: "Paris, France", offset: "UTC+1/+2" },
  { value: "Europe/Berlin", label: "Berlin, Germany", offset: "UTC+1/+2" },
  { value: "Europe/Rome", label: "Rome, Italy", offset: "UTC+1/+2" },
  { value: "Europe/Madrid", label: "Madrid, Spain", offset: "UTC+1/+2" },
  { value: "Europe/Amsterdam", label: "Amsterdam, Netherlands", offset: "UTC+1/+2" },
  { value: "Europe/Brussels", label: "Brussels, Belgium", offset: "UTC+1/+2" },
  { value: "Europe/Vienna", label: "Vienna, Austria", offset: "UTC+1/+2" },
  { value: "Europe/Zurich", label: "Zurich, Switzerland", offset: "UTC+1/+2" },
  { value: "Europe/Stockholm", label: "Stockholm, Sweden", offset: "UTC+1/+2" },
  { value: "Europe/Copenhagen", label: "Copenhagen, Denmark", offset: "UTC+1/+2" },
  { value: "Europe/Oslo", label: "Oslo, Norway", offset: "UTC+1/+2" },
  { value: "Europe/Helsinki", label: "Helsinki, Finland", offset: "UTC+2/+3" },
  { value: "Europe/Warsaw", label: "Warsaw, Poland", offset: "UTC+1/+2" },
  { value: "Europe/Prague", label: "Prague, Czech Republic", offset: "UTC+1/+2" },
  { value: "Europe/Budapest", label: "Budapest, Hungary", offset: "UTC+1/+2" },
  { value: "Europe/Athens", label: "Athens, Greece", offset: "UTC+2/+3" },
  { value: "Europe/Istanbul", label: "Istanbul, Turkey", offset: "UTC+3" },
  { value: "Europe/Moscow", label: "Moscow, Russia", offset: "UTC+3" },
  { value: "Europe/Kiev", label: "Kyiv, Ukraine", offset: "UTC+2/+3" },

  // Asia
  { value: "Asia/Tokyo", label: "Tokyo, Japan", offset: "UTC+9" },
  { value: "Asia/Shanghai", label: "Shanghai, China", offset: "UTC+8" },
  { value: "Asia/Hong_Kong", label: "Hong Kong", offset: "UTC+8" },
  { value: "Asia/Singapore", label: "Singapore", offset: "UTC+8" },
  { value: "Asia/Seoul", label: "Seoul, South Korea", offset: "UTC+9" },
  { value: "Asia/Taipei", label: "Taipei, Taiwan", offset: "UTC+8" },
  { value: "Asia/Bangkok", label: "Bangkok, Thailand", offset: "UTC+7" },
  { value: "Asia/Jakarta", label: "Jakarta, Indonesia", offset: "UTC+7" },
  { value: "Asia/Manila", label: "Manila, Philippines", offset: "UTC+8" },
  { value: "Asia/Kuala_Lumpur", label: "Kuala Lumpur, Malaysia", offset: "UTC+8" },
  { value: "Asia/Ho_Chi_Minh", label: "Ho Chi Minh City, Vietnam", offset: "UTC+7" },
  { value: "Asia/Mumbai", label: "Mumbai, India", offset: "UTC+5:30" },
  { value: "Asia/Kolkata", label: "Kolkata, India", offset: "UTC+5:30" },
  { value: "Asia/Delhi", label: "New Delhi, India", offset: "UTC+5:30" },
  { value: "Asia/Dhaka", label: "Dhaka, Bangladesh", offset: "UTC+6" },
  { value: "Asia/Karachi", label: "Karachi, Pakistan", offset: "UTC+5" },
  { value: "Asia/Tashkent", label: "Tashkent, Uzbekistan", offset: "UTC+5" },
  { value: "Asia/Almaty", label: "Almaty, Kazakhstan", offset: "UTC+6" },
  { value: "Asia/Yekaterinburg", label: "Yekaterinburg, Russia", offset: "UTC+5" },
  { value: "Asia/Novosibirsk", label: "Novosibirsk, Russia", offset: "UTC+7" },
  { value: "Asia/Vladivostok", label: "Vladivostok, Russia", offset: "UTC+10" },

  // Middle East
  { value: "Asia/Dubai", label: "Dubai, UAE", offset: "UTC+4" },
  { value: "Asia/Riyadh", label: "Riyadh, Saudi Arabia", offset: "UTC+3" },
  { value: "Asia/Kuwait", label: "Kuwait City, Kuwait", offset: "UTC+3" },
  { value: "Asia/Qatar", label: "Doha, Qatar", offset: "UTC+3" },
  { value: "Asia/Bahrain", label: "Manama, Bahrain", offset: "UTC+3" },
  { value: "Asia/Tehran", label: "Tehran, Iran", offset: "UTC+3:30/+4:30" },
  { value: "Asia/Baghdad", label: "Baghdad, Iraq", offset: "UTC+3" },
  { value: "Asia/Jerusalem", label: "Jerusalem, Israel", offset: "UTC+2/+3" },
  { value: "Asia/Beirut", label: "Beirut, Lebanon", offset: "UTC+2/+3" },
  { value: "Asia/Damascus", label: "Damascus, Syria", offset: "UTC+2/+3" },

  // Africa
  { value: "Africa/Cairo", label: "Cairo, Egypt", offset: "UTC+2" },
  { value: "Africa/Johannesburg", label: "Johannesburg, South Africa", offset: "UTC+2" },
  { value: "Africa/Lagos", label: "Lagos, Nigeria", offset: "UTC+1" },
  { value: "Africa/Nairobi", label: "Nairobi, Kenya", offset: "UTC+3" },
  { value: "Africa/Casablanca", label: "Casablanca, Morocco", offset: "UTC+0/+1" },
  { value: "Africa/Tunis", label: "Tunis, Tunisia", offset: "UTC+1" },
  { value: "Africa/Algiers", label: "Algiers, Algeria", offset: "UTC+1" },
  { value: "Africa/Addis_Ababa", label: "Addis Ababa, Ethiopia", offset: "UTC+3" },
  { value: "Africa/Dar_es_Salaam", label: "Dar es Salaam, Tanzania", offset: "UTC+3" },
  { value: "Africa/Kampala", label: "Kampala, Uganda", offset: "UTC+3" },
  { value: "Africa/Khartoum", label: "Khartoum, Sudan", offset: "UTC+2" },
  { value: "Africa/Accra", label: "Accra, Ghana", offset: "UTC+0" },

  // Oceania
  { value: "Australia/Sydney", label: "Sydney, Australia", offset: "UTC+10/+11" },
  { value: "Australia/Melbourne", label: "Melbourne, Australia", offset: "UTC+10/+11" },
  { value: "Australia/Brisbane", label: "Brisbane, Australia", offset: "UTC+10" },
  { value: "Australia/Perth", label: "Perth, Australia", offset: "UTC+8" },
  { value: "Australia/Adelaide", label: "Adelaide, Australia", offset: "UTC+9:30/+10:30" },
  { value: "Australia/Darwin", label: "Darwin, Australia", offset: "UTC+9:30" },
  { value: "Pacific/Auckland", label: "Auckland, New Zealand", offset: "UTC+12/+13" },
  { value: "Pacific/Fiji", label: "Suva, Fiji", offset: "UTC+12/+13" },
  { value: "Pacific/Tahiti", label: "Tahiti, French Polynesia", offset: "UTC-10" },
  { value: "Pacific/Guam", label: "Guam", offset: "UTC+10" },

  // UTC Options
  { value: "UTC", label: "UTC (Coordinated Universal Time)", offset: "UTC+0" },
  { value: "GMT", label: "GMT (Greenwich Mean Time)", offset: "UTC+0" },
]

export const LANGUAGES = [
  { value: "en", label: "English" },
  { value: "es", label: "Español (Spanish)" },
  { value: "fr", label: "Français (French)" },
  { value: "de", label: "Deutsch (German)" },
  { value: "it", label: "Italiano (Italian)" },
  { value: "pt", label: "Português (Portuguese)" },
  { value: "ru", label: "Русский (Russian)" },
  { value: "ja", label: "日本語 (Japanese)" },
  { value: "ko", label: "한국어 (Korean)" },
  { value: "zh", label: "中文 (Chinese)" },
  { value: "ar", label: "العربية (Arabic)" },
  { value: "hi", label: "हिन्दी (Hindi)" },
  { value: "nl", label: "Nederlands (Dutch)" },
  { value: "sv", label: "Svenska (Swedish)" },
  { value: "no", label: "Norsk (Norwegian)" },
  { value: "da", label: "Dansk (Danish)" },
  { value: "fi", label: "Suomi (Finnish)" },
  { value: "pl", label: "Polski (Polish)" },
  { value: "tr", label: "Türkçe (Turkish)" },
  { value: "th", label: "ไทย (Thai)" },
]